apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: try-today-gitops
  description: This is GitOps manifest for try-today   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: try-today
    janus-idp.io/tekton: try-today 
    backstage.io/kubernetes-id: try-today 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:try-today
